# Utilise une image Python officielle
FROM python:3.12

ENV app=/opt/api
RUN mkdir -p $app
WORKDIR $app
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1
RUN pip install --upgrade pip

COPY obackend/ $app
RUN pip install -r requirements.txt

EXPOSE 8000

CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]