version: '3.8'

services:
  db:
    image: mariadb:latest
    container_name: mariadb_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: azerty
      MYSQL_DATABASE: auto_ecole_db
      MYSQL_USER: aecole
      MYSQL_PASSWORD: aecole
    volumes:
      - ./db_data:/var/lib/mysql
    networks:
      - app-network
    ports:
      - "9089:3306"

  backend:
    build: 
      context: .
      dockerfile: Dockerfile.back
    container_name: django_backend_container
    restart: always

      
    command: sh -c "python manage.py waitdb &&
                    yes |python manage.py makemigrations &&
                    python manage.py migrate &&
                    python manage.py initsu &&
                    python manage.py runserver 0.0.0.0:8000"

    volumes:
      - ./obackend:/opt/api:z
    
    environment:
      - DB_HOST=db
      - DB_NAME=auto_ecole_db
      - DB_USER=example_user
      - DB_PASSWORD=example_password
      - ADMIN_USER=azkone
      - ADMIN_PASS=azkone
      - ADMIN_EMAIL=azkone@a.com
    depends_on:
      - db
    networks:
      - app-network
    ports:
      - "9090:8000"

  flutter_web:
    build:
      context: .
      dockerfile: Dockerfile.flutter
    container_name: epik_app
    networks:
      - app-network
    ports:
      - "8081:80"
    volumes:
      - ./ofront:/usr/share/nginx/html:ro

  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    depends_on:
      - flutter_web
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf # Nginx configuration
      - ./certs:/etc/nginx/certs # Folder for SSL certificates
    ports:
      - "80:80"
      - "443:443"
    networks:
      - app-network
  
volumes:
  db_data:

networks:
  app-network:
    driver: bridge