# Generated by Django 5.1 on 2024-08-18 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrollment',
            name='completed',
        ),
        migrations.AddField(
            model_name='student',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='student',
            name='enrollement_completed',
            field=models.BooleanField(default=False),
        ),
    ]
