# Generated by Django 5.1 on 2024-08-29 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_enrollment_completed_student_amount_paid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='logo',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='instructor',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='instructor',
            name='pID',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
