# Generated by Django 5.1 on 2024-08-30 06:29

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_instructor_logo_instructor_name_instructor_pid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructor',
            name='logo',
            field=models.ImageField(null=True, upload_to=api.models.Instructor.upload_to),
        ),
    ]
