# Generated by Django 5.1 on 2024-08-31 04:56

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_instructor_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='telephone',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=api.models.Instructor.upload_to),
        ),
    ]
