# Generated by Django 5.1 on 2024-09-02 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_instructor_telephone_alter_instructor_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='num_piece',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
