# Generated by Django 5.1 on 2024-09-04 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_student_num_piece'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='qid',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
