# Generated by Django 5.1.1 on 2024-09-14 00:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_student_qid'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='capp',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='instructor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.instructor'),
        ),
    ]
